#!/usr/bin/perl

use 5.14.0;
use strict;
use warnings;
use File::Spec 0.80;
use Config::Tiny 2.12;
use ADAMK::Dancer2::Twittersect;

my $server = ADAMK::Dancer2::Twittersect->new(
	config => Config::Tiny->read("twittersect.conf")
);

$server->run;
